spring.application.name=MegaSOAT Monitoring Service
server.port=8081
spring.main.allow-bean-definition-overriding=true
spring.datasource.url=jdbc:mysql://bn3ramkmisijqjhjjukm-mysql.services.clever-cloud.com:3306/bn3ramkmisijqjhjjukm?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Lima&useUnicode=true&characterEncoding=UTF-8
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=u0oekml0dqi9glb4
spring.datasource.password=IytT4lhnstJTpmzUUtEM
spring.jpa.hibernate.ddl-auto=none
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=mega-soat-secret-key-change-me
jwt.expiration-ms=86400000
logging.level.org.springframework.security=INFO
